services:
  jd-mobile:
    image: ghcr.io/thehack904/jd-mobile:latest
    container_name: jd-mobile
    environment:
      - JD_MOBILE_CONFIG_PATH=${JD_MOBILE_CONFIG_PATH:-/app/config/config.json}
    volumes:
      - ${JD_MOBILE_HOST_CONFIG_DIR}:/app/config
    ports:
      - "0.0.0.0:${JD_MOBILE_PORT:-8086}:8086"
    restart: unless-stopped
