services:
  jd-mobile:
    container_name: jd-mobile
    image: ghcr.io/thehack904/jd-mobile:latest
    restart: unless-stopped
    ports:
     - "8086:8086"
    environment:
      - JD_MOBILE_CONFIG_PATH=${JD_MOBILE_CONFIG_PATH:-/app/config/config.json}
    volumes:
      - ./config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086"]
      interval: 30s
      timeout: 5s
      retries: 3
